import type { Metadata } from 'next'

import Providers from './providers'

import '@repo/ui/styles.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' data-theme='light'>
      <body className='panorama-normalize'>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
